version: '3.0'


services:
  #realworld:
  #  privileged: true
  #  build:
  #    context: .
  #    dockerfile: Dockerfile-debug
  #  image: realworld:latest
  #  ports:
  #    - 2000:2000
  #    - 2001:2001
  #    - 2002:2002
  #    - 2003:2003
  #    - 2004:2004
  #    - 2005:2005
  #    - 2006:2006
  #    - 2007:2007
  #    - 2008:2008
  #    - 2009:2009
  #    - 2010:2010
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      .env
    ports:
      - 5433:5432
  
volumes: 
  pgdata: